# Generated by Django 2.2.24 on 2025-07-05 09:55

from django.db import migrations, models


def add_flat_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')


    flats_by_name = {}
    flats = Flat.objects.all()
    for flat in flats.iterator():
        key = flat.owner.strip().lower()
        flats_by_name.setdefault(key, []).append(flat)
    for owner in Owner.objects.iterator():
        key = owner.name.strip().lower()
        flats = flats_by_name.get(key, [])
        owner.flats.set(flats)


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.flats.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20250705_1255'),
    ]

    operations = [
        migrations.RunPython(add_flat_to_owner, move_backward),
    ]
