# Generated by Django 2.2.24 on 2025-07-05 09:55

from django.db import migrations, models


def add_flat_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')


    flats_by_phonenumber = {}
    all_flats = Flat.objects.all()
    for flat in all_flats.iterator():
        owner_phone_key = flat.owner_pure_phone.strip()
        flats_by_phonenumber.setdefault(owner_phone_key, []).append(flat)
    for owner in Owner.objects.iterator():
        owner_phone_key = owner.owner_pure_phone.strip()
        flats = flats_by_phonenumber.get(owner_phone_key, [])
        owner.flats.set(flats)


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.flats.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20250705_1255'),
    ]

    operations = [
        migrations.RunPython(add_flat_to_owner, move_backward),
    ]
