# Generated by Django 5.2.4 on 2025-08-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_complaint_author_alter_complaint_flat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
